# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcad54c60cacaeec1e161adbc7ff673f113f69ae6e89d5a1359d3297528cfafe29afc8f9661c0ff0c2bfb19697e87b374abc302ea3c3d58bac68e8500c1e6132

test:
  secret_key_base: 9287ceb4091a5c1da10ce641dab852db13a12e5baa101a89ab06fdc148a69357e6365374e821528dc57c0249bf45749c601c3842d8a823ad36bb006769de4103

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
